#!/usr/bin/env bash
# install load balancer for performtrack.tech

echo -e "Updating and doing some minor checks...\n"

function install() {
    command -v "$1" &> /dev/null

    # shellcheck disable=SC2181
    if [ $? -ne 0 ]; then
        echo -e "	Installing: $1\n"
        sudo apt-get update -y -qq && \
            sudo apt-get install -y "$1" -qq
        echo -e "\n"
    else
        echo -e "	${1} is already installed.\n"
    fi
}

install haproxy # Install haproxy

echo -e "\nSetting up some minor stuff.\n"

# Backup default server config file
sudo cp /etc/haproxy/haproxy.cfg haproxy_default.backup

server_config=\
"
defaults
  mode http
  timeout client 15s
  timeout connect 10s
  timeout server 15s
  timeout http-request 10s

frontend performtrack-tech-frontend
    bind *:80
    default_backend performtrack-tech-backend

backend performtrack-tech-backend
    balance roundrobin
    server 192094-web-01 52.201.162.187:80 check
    server 192094-web-02 18.207.233.234:80 check
"

# shellcheck disable=SC2154
echo "$server_config" | sudo dd status=none of=/etc/haproxy/haproxy.cfg

# Enable haproxy to be started by init script
echo "ENABLED=1" | sudo dd status=none of=/etc/default/haproxy

# Start or restart haproxy service
if [ "$(pgrep -c haproxy)" -le 0 ]; then
    sudo service haproxy start
else
    sudo service haproxy restart
fi

echo -e "Load Balancer configured - Roundrobin On web-01 & web-02"
echo "web-01 (52.201.162.187)"
echo "web-02 (18.207.233.234)"

