#!/bin/bash

sed -i 's/^user .*/user nginx;/; s/listen [0-9]*;/listen 8080;/' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/' /etc/nginx/sites-available/default
chown -R nginx:nginx /var/log/nginx /var/cache/nginx
systemctl restart nginx

ps aux | grep [n]ginx
nc -z 0 8080

